---
title: "Books and Resources"
---

## Core Reading

Books directly related to the course topics.

### Stream Processing

1. G. Shapira, T. Palino, R. Sivaram, K. Petty -- _Kafka: The Definitive Guide. Real-time data and stream processing at scale_, 2nd ed., O'Reilly 2022. [Free access](https://www.confluent.io/resources/kafka-the-definitive-guide-v2/)
2. G. Maas, F. Garillot -- _Stream Processing with Apache Spark_, O'Reilly 2019. [Description](https://helion.pl/view/111546/e_11pp.html)
3. F. Hueske, V. Kalavri -- _Stream Processing with Apache Flink_, O'Reilly 2019. [Description](https://helion.pl/view/111546/e_13f8.html)
4. A. Bellemare -- _Building Event-Driven Microservices_, O'Reilly 2021. [Description](https://helion.pl/view/111546/miopzd)
5. T. Akidau, S. Chernyak, R. Lax -- _Streaming Systems: The What, Where, When, and How of Large-Scale Data Processing_, O'Reilly 2018.
6. J. Korstanje -- _Machine Learning for Streaming Data with Python_, Packt 2022.

### Apache Spark

1. J. S. Damji, B. Wenig, T. Das, D. Lee -- _Learning Spark_, 2nd ed., O'Reilly 2020.
2. B. Chambers, M. Zaharia -- _Spark: The Definitive Guide_, O'Reilly 2018. [Description](https://helion.pl/view/111546/e_0qdv.html)
3. J. Quddus -- _Machine Learning with Apache Spark Quick Start Guide_, Packt. [Description](https://helion.pl/view/111546/e_15el.html)

### MLOps and Model Deployment

1. N. Gift, A. Deza -- _Practical MLOps: Operationalizing Machine Learning Models_, O'Reilly 2022.
2. V. Lakshmanan, S. Robinson, M. Munn -- _Machine Learning Design Patterns_, O'Reilly 2021.


## Supplementary Reading

### Machine Learning with Python

1. A. Geron -- _Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow_, 2nd ed., O'Reilly. [Description](https://helion.pl/view/111546/uczem2.html)
2. W. McKinney -- _Python for Data Analysis_, 2nd ed., O'Reilly. [Description](https://helion.pl/view/111546/pytand.html)
3. J. Grus -- _Data Science from Scratch_, 2nd ed., O'Reilly. [Description](https://helion.pl/view/111546/dascp2.html)
4. S. Raschka -- _Python Machine Learning_, 2nd ed., Packt. [Description](https://helion.pl/view/111546/pythu2.html)
5. T. Hastie, R. Tibshirani, J. Friedman -- _The Elements of Statistical Learning_, Springer 2017. [Free access](https://hastie.su.domains/ElemStatLearn/)

### Deep Learning

1. F. Chollet -- _Deep Learning with Python_, Manning. [Description](https://helion.pl/view/111546/delepy.html)
2. J. Howard, S. Gugger -- _Deep Learning for Coders with fastai and PyTorch_, O'Reilly. [Description](https://helion.pl/view/111546/delepr.html)
3. A. Koul, S. Ganju, M. Kasam -- _Practical Deep Learning for Cloud, Mobile & Edge_, O'Reilly 2019.

### Docker and Tools

1. J. Krochmalski -- _Docker: Up & Running_, O'Reilly. [Description](https://helion.pl/view/111546/docpro.html)
2. P. Bell, B. Beer -- _Introducing GitHub_, O'Reilly. [Description](https://helion.pl/view/111546/github.html)

### Python

1. C. Althoff -- _The Self-Taught Programmer_, Triangle Connection 2017. [Description](https://helion.pl/view/111546/proprs)
2. A. Sweigart -- _Automate the Boring Stuff with Python_, No Starch Press. [Description](https://helion.pl/view/111546/autopy)

### Quantum Computing

1. A. Jacquier, O. Kondratyev -- _Quantum Machine Learning and Optimisation in Finance: On the Road to Quantum Advantage_.


## Useful Websites

### Software

1. [GitHub](https://github.com/)
2. [Git documentation](https://git-scm.com/book/en/v2)
3. [Python](https://www.python.org/downloads/)
4. [PyPI -- Python Package Index](https://pypi.python.org/pypi)
5. [Docker](https://docs.docker.com/get-docker/)
6. [Apache Kafka](https://kafka.apache.org/)
7. [Apache Spark](https://spark.apache.org/)

### Python Libraries

1. [NumPy](https://numpy.org)
2. [Pandas](https://pandas.pydata.org)
3. [Scikit-learn](https://scikit-learn.org/stable)
4. [Matplotlib](https://matplotlib.org)
5. [JupyterLab](https://jupyter.org)
6. [TensorFlow](https://www.tensorflow.org)
7. [Keras](https://keras.io)
8. [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup)

### Editor

1. [Visual Studio Code](https://code.visualstudio.com)

### Datasets

- [Kaggle Datasets](https://www.kaggle.com/datasets)
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [UCI Machine Learning Repository](https://archive.ics.uci.edu/)
- [Reddit r/datasets](https://reddit.com/r/datasets)
- [Public APIs](https://github.com/toddmotto/public-apis)
- [KDnuggets](https://www.kdnuggets.com)

### Courses and Tutorials

1. [Machine Learning -- Andrew Ng (YouTube)](https://www.youtube.com/watch?v=PPLop4L2eGk&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN)
2. [Python Programming for Data Science -- T. Beuzen](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html)
3. [Chris Albon -- Data Science & AI Notes](https://chrisalbon.com/)
